### ISSUE TITLE
Possible bug when trying to replace strings ending with a colon

### ISSUE THREAD

**Issue by andrea-perego** [w3c/scribe2#1]
This happened today in these meeting minutes (go to the end of the page):

https://www.w3.org/2019/07/31-dxwgdcat-minutes

Commands like 

````
s/plh: E.g., within the/PWinstanley: E.g., within the/
````

were added to the minutes as 

> **s/plh:** E.g., within the/PWinstanley: E.g., within the/ 

thus considering **s/plh:** as a nickname.

NB: This does not happen if you generate the minutes with the old version of the script.

**Comment by bert-github** [comment]
The "s/plh: ..." line failed to substitute anything and scribe.perl then tried other ways to interpret it. In this case it could be interpreted as a line for a speaker called "s/plh".

I changed the code to not interpret failed s/// lines again. They are now always output as-is, i.e., as normal IRC messages.

I asked for RRSagent to be updated with this new version.
