### ISSUE TITLE
Feature request: add per-line IDs to the generated output

### ISSUE THREAD

**Issue by swickr** [w3c/scribe2#2]
To be able to cite specific points in minutes it would be very handy to have IDs on each line.

E.g. 

> &lt;p class="phone s11" id="L2048"&gt; &lt;cite&gt;speaker:&lt;/cite&gt; ... &lt;/p&gt;

Numerically increasing IDs are acceptable, recognizing that these are subject to change when the minutes are regenerated.

**Comment by bert-github** [comment]
Done in version 110. Every <p> has an ID. And if a <p> has multiple lines, the 2nd and subsequent lines have IDs of their own.

The IDs are simple incrementing numbers, not based on the structure or the content and they may indeed turn out different if you regenerate the minutes after adding a s/// or i/// command, or after changing certain script options, such as -nokeeplines.

If browsers implemented Xpointer, this wouldn't be necessary…
