### ISSUE TITLE
Add 'participants:' list

### ISSUE THREAD

**Issue by swickr** [w3c/scribe2#22]
I would find it useful to have a list of those who were minuted as speaking or who made a comment in irc.  This could be added in the diagnostics section as my use case is to help in cleaning the minutes post-meeting.

This would be in addition to, not replacing, the existing diagnostic "Maybe present:"

**Comment by bert-github** [comment]
I added ‘All speakers’ and ‘Active on IRC’ to the diagnostics. The latter does not include known bots.

Let me know if this is not what you want.
