### ISSUE TITLE
More robust heading identifiers

### ISSUE THREAD

**Issue by pchampin** [w3c/scribe2#27]
Currently, scribe2 generates identifiers (attribute `id`) in sequence (`t01`, `t02`, `t03`...), regardless of the hierarchy (`h3`, `h4`).
For example:

* topic 1 → `#t01`
  - subtopic 1.1 → `#t02`
  - subtopic 1.2 → `#t03`
* topic 2 → `#t04`
  - subtopic 2.1 → `#t05`
  - subtopic 2.2 → `#t06`

I propose to reflect the hierarchy of headings in the identifiers, for example:

* topic 1 → `#t01`
  - subtopic 1.1 → `#t01_01`
  - subtopic 1.2 → `#t01_01`
* topic 2 → `#t02`
  - subtopic 2.1 → `#t02_01`
  - subtopic 2.2 → `#t02_02`

This would make the identifiers more robust to changes in the stucture when the minutes are cleaned.
For example, if a subtopic is added or removed in topic 1, this will change the identifiers of all subsequent headings, including in topic 2. With the proposed approach, the impact would be limited to subsequent subtopics of topic 1.

**Comment by pchampin** [comment]
This issue is motivated by my own bot https://github.com/pchampin/minutes_to_gh. That bot is meant to be used after the minutes have been cleaned and generated. But there is always a risk that someone further cleans the minutes after the github comments have been posted.

If that happens, there is a risk that some links posted to github become invalid. With the proposal above, this risk much lower (although not null).

**Comment by pchampin** [comment]
Additional thoughts: if the id of every utterance was prefixed by the id of the (sub)topic in which it occurs, this would make linking to minutes more robust in general.

**Comment by bert-github** [comment]
How about not using sequence numbers for the IDs at all, but using a hash of the text content of the line? Only lines that hash to the same value will have a different ID that is influenced by earlier lines.

In that case you can add or remove lines or topics without affecting the IDs of later lines. Only if the added/removed line happens to have the same hash as another line, will it influence that other line's ID and only that one.

I did some experiments with an unsophisticated hash function that I just made up and that outputs a 16-bit number (to keep the numbers short). It adds a bit to the processing time (some 6% on the processing of a fairly big file) but that seems the only disadvantage so far.

The HTML will look something like this:

    <li><a href="#4bf8">Heading</a></li>
    ...
    <h3 id=4bf8>Heading</h3>
    <p id=d8cf class=summary>...</p>
    <p id=e5f6 class="phone s08">...</p>

You can see the result in the branch ‘hash-ids’. The tests have not been updated, but you can look at the sample*.html files to see how the IDs look.

**Comment by pchampin** [comment]
I like that a lot :)

**Comment by pchampin** [comment]
thought: you probably want to include the timestamp in your hash because duplicate utterance do happen (e.g. "+1" :)

**Comment by bert-github** [comment]
The time stamp is not always available. (It is when processing IRC logs made by RRSAgent, but some other log formats do not include times.) And the combination of text and time stamp is still not always unique. It is possible that two people type the same text in the same second, especially if the text is ‘+1’,

At the moment, if the computed hash of a line is not a unique number, it is simply incremented until it is.

First experiments with adding the time stamp to the hash don't show a noticeable difference. There is usually only a small number of identical lines and most occurrences of identical hashes are not due to those, but simply because different inputs will occasionally produce the same hash, as the hash is only 16 bits. Some input files produce fewer identical hashes when the time stamp is added, others produce more.

**Comment by bert-github** [comment]
The solution that is using a hash of the text content as the ID is now deployed.

I'll see if I can make some statistics and check if there are possible improvements, but for now it seems to work.

**Comment by bert-github** [comment]
The latest version, revision 237, uses each line's timestamp (if any) as the seed value for the hash function. That doesn't increase the computing time and still avoids one or two hash conflicts between lines.

This version also speeds things up by only computing hash values for lines that will actually be printed.
