### ISSUE TITLE
plaintext element

### ISSUE THREAD

**Issue by xfq** [w3c/scribe2#32]
https://www.w3.org/2024/12/19-i18n-minutes.html#6b83

There seems to be something wrong with the text above. Is `<plaintext>` the reason?

**Comment by bert-github** [comment]
It was a forgotten call to the subroutine to escape HTML delimiters in a part of the text. Now fixed

Thanks for reporting!

**Comment by xfq** [comment]
I confirm that All Goes Well now. Thank you, Bert!
