### ISSUE TITLE
Disclosure widget for the list of attendees

### ISSUE THREAD

**Issue by xfq** [w3c/scribe2#5]
Some meetings I attended had a lot of (100+) participants and the list of attendees take up too much space. It would be great if there is an option to add a disclosure widget (like [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) in HTML) to the present list header.

**Comment by bert-github** [comment]
Done in version 123.

Except that I didn't make it an option: A DETAILS element is now generated whenever there are more than 30 participants.

Should it be an option instead? Should it depend on something else? Should the number be configurable?

**Comment by xfq** [comment]
Other people might want to make it configurable, but it is enough for me, thank you!

**Comment by bert-github** [comment]
There is now (in version 129) an option --collapseLimit, which can be used from command line or via the scribeoptions command on IRC. The default is 30.

As all options, it can be abbreviated, e.g.:

    scribeoptions: -collapse 30
