### ISSUE TITLE
Zero-width non-joiner in URLs

### ISSUE THREAD

**Issue by xfq** [w3c/scribe2#6]
scribe.perl seems to [insert](https://github.com/w3c/scribe2/blob/7b6e43ffe429f2a7325bd8112ff6b932dca8f6d4/scribe.perl#L323-L335) `&zwnj;` after slashes in URLs. This is great, but I see two issues:

1. Some long URLs will still overflow (such as [this one](https://www.w3.org/2020/10/22-dap-minutes.html#x277)).
2. If the user copies the URL and pastes it in the browser address bar or in another application like an email client (instead of clicking the link directly), the URL is 404. Perhaps inserting [wbr](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-wbr-element) before all punctuation marks is more appropriate?

**Comment by bert-github** [comment]
On 2020-10-25 04:36, Fuqiao Xue wrote:
> scribe.perl seems to insert 
> <https://github.com/w3c/scribe2/blob/7b6e43ffe429f2a7325bd8112ff6b932dca8f6d4/scribe.perl#L323-L335> 
> |&zwnj;| after slashes in URLs. This is great, but I see two issues:
> 
>  1. Some long URLs will still overflow (such as this one
>     <https://www.w3.org/2020/10/22-dap-minutes.html#x277>).

I now added 'overflow-wrap: break-word' to the style sheet.

It is still a proposed property, but it works in some browsers. (I'll 
watch out for any changes in the specifications.)

>  2. If the user copies the URL and pastes it in the browser address bar
>     or in another application like an email client (instead of clicking
>     the link directly), the URL is 404. Perhaps inserting wbr
>     <https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-wbr-element>
>     before all punctuation marks is more appropriate?

You can also do right click and copy, in most browsers. But <wbr> looks 
like a good idea, indeed.

Done in version 123.

-- 
   Bert Bos                                ( W 3 C ) http://www.w3.org/
   http://www.w3.org/people/bos                               W3C/ERCIM
   bert@w3.org                             2004 Rt des Lucioles / BP 93
   +33 (0)4 92 38 76 92            06902 Sophia Antipolis Cedex, France
