### ISSUE TITLE
link/crosslink for rescue.html 

### ISSUE THREAD

**Issue by koalie** [w3c/scribe2#7]
Hi Bert,

Perhaps you could cross link or refer to rescue.html from https://www.w3.org/2002/03/RRSAgent ?

**Comment by bert-github** [comment]
Linked from

- https://www.w3.org/Guide/ near Zakim and RRSAgent
- https://w3c.github.io/scribe2/scribedoc.html in the ‘nearby’ box
- https://www.w3.org/2008/04/scribe.html in the ‘nearby’ box

I'll leave https://www.w3.org/2002/03/RRSAgent for @swickr to decide.

**Comment by swickr** [comment]
Thanks for the suggestion @koalie and the mention @bert-github -- [done](https://www.w3.org/2002/03/RRSAgent#formatMinutes)!
